name: spatial-inequality
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - matplotlib=3.4.1
  - jupyter=1.0.0
  - descartes=1.1.0
  - pygmo=2.16.1
  - contextily=1.1.0
  - seaborn=0.11.1
  - pip:
    - -e .
